### ISSUE TITLE
Students can only view own annotations

### ISSUE THREAD

**Issue by sleepers1980** [rwthmoodle/moodle-mod_pdfannotator#32]
How can I setup that students can only view their own comments?
If there is no way by setting options or rights in moodle, where (file, lines) do I have to change the code?

**Comment by Friederike-cil** [comment]
There is no way to do this (except the students download the pdf-file and use an external program for commenting).

So this is what you have to do in order to have private comments/annotations:
You should use the visibility attribute of the comments (currently it can be 'public' or 'anonymous', so add a third option 'private').  For posting privately you could a checkbox to the comment form similar to the '#anonymousCheckbox' in the template index.mustache. In index.js lines 1882ff you have to set the value of commentVisibility correctly.
For displaying only non-private annotations on the document you have to modify action.php line 66 ($action === 'read). Skip each annotation ($record) whose author (userid) is not the current user and whose first comment is private. For this retreive the comment with the corresponding annotationid and isquestion=1 from the DB and check its visibility. 
For displaying only non-private comments modify the function read in comment.class.php in line 159. In the foreach loop skip every comment whose visibility is private and whose author is not the current user. Or don't even retreive those comments from the DB by changing the preceding SQL-statement. You should also change the method set_username (comment.class.php line 208) and add a case 'private'.
On the overview tab don't display private comments by other useres too. Skip them in locallib.php, function pdfannotator_get_questions, line 741 (question) and line 754 (last answer to this question), function pdfannotator_get_answers_for_this_user after line 922. Or don't retreive them from the DB.
For the column next to the document do the same: Change the SQL-Statements or the foreach-loop in comment.class.php in the functions get_questions, get_all_questions and get_questions_search.
For higher security you should also prevent a user from subscribing to questions he is not allowed to see in comment.class.php function insert_subscription. And don't send notifications about new private answers or questions (comment.class.php, function create, lines 94 and 116).

If all comments/annotations should be private you don't have to use the visibility attribute. Just check for the author at the mentioned lines.
If you want private annotations (including all their comments) and you don't want private comments to public annotations, it might be better to add a visibility-field to the pdfannotator_annotations table.

**Comment by Friederike-cil** [comment]
Hi, 
we are implementing this feature now and will release it soon

Kind regards
Friederike
