### ISSUE TITLE
Error when answering to an annotation

### ISSUE THREAD

**Issue by babicht** [rwthmoodle/moodle-mod_pdfannotator#95]
We get the following error when answering to any annotation:
![image](https://github.com/rwthmoodle/moodle-mod_pdfannotator/assets/136691601/1276372f-6c76-4719-91bc-c2add8723324)

Moodle-Version 4.1.4
Plugin-Version PDF Annotator v1.5 release 4 (2023052300)

**Comment by nisaDoc** [comment]
Hello,

thx for reporting this issue. I would think, this issue is the same with #96. It looks like, you are using TinyMCE Editor, that this plugin does not support (see release note for v1.5.1).
I would recommend you to using atto editor, which the only editor we support.
We have added an issue for supporting tinymce in our backlog too. But, due to other projects, I cannot give you guarantie, when we will develope it.

Cheers,
Nisa

**Comment by Friederike-cil** [comment]
Hi,
it's fixed in the latest release 1.5.5
