### ISSUE TITLE
Error invalid course ID

### ISSUE THREAD

**Issue by lf1717** [rwthmoodle/moodle-mod_pdfannotator#96]
Hi,

We implemented the plugin PDF Annotation Activity to our Moodle (Version 4.1.3 (Build: 20230424)). 

When I will reply to a question or comment I get the error of invalid course ID:
![image](https://github.com/rwthmoodle/moodle-mod_pdfannotator/assets/108652528/ad639f94-34ff-4190-9ae4-6d6002c9b456)

Why does this happen? Thanks for your help. 

Regards,
Lydia

**Comment by nisaDoc** [comment]
Hello,
thx for reporting this issue, could you provide more infos for this problem? When did this appear? How? and could you also tell us also what in the stack trace is?
Thx

Cheers,
Nisa

**Comment by lf1717** [comment]
Hi Nisa, 
This appears when I would like to answer to a comment. watch my video:

https://github.com/rwthmoodle/moodle-mod_pdfannotator/assets/108652528/3ccfb273-221d-49a6-8403-1df6b6dac710

I don't have access to the stack trace. I have to ask our hosting partner. 

Regards, 
Lydia

**Comment by nisaDoc** [comment]
Thx you for the infos. 
I know whats the problem.
Because, you are using the editor Tiny MCE. PDFAnnotator do not support this editor. We just support the atto editor as our standard. It was written in our release v1.5.1 (https://github.com/rwthmoodle/moodle-mod_pdfannotator/releases/tag/v.1.5.1)
But, we have added this as an issue for supporting tiny mce editor in our backlog. Due other projects I cannot guarantie when we will support this editor. As Workarround, you should use Atto editor as standard.

Cheers,
Nisa

**Comment by lf1717** [comment]
Hi Nisa,
Thanks for the "solution". Yes I will use the Atto as workaround and I hope, we could use the plugin with the tiny mce soon in future. 

Regards
Lydia

**Comment by Friederike-cil** [comment]
Hi,
it's fixed in the latest release 1.5.5
